name = "chaotic-design"
type = "webpack"
account_id = "242676fc941b10ce3c60779f906dcc00"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
workers_dev = false
routes = [ "*.chaoticdesign.io/*", "chaoticdesign.io/*" ]
zone_id = "363a12a81eba21740dd71ecb0152e7c1"

[env.staging]
workers_dev = true
route = ""
zone_id = ""