name: Build Branch
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Navigate to workspace
        run: cd $GITHUB_WORKSPACE
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - name: Build assets
        run: npm run build